### ISSUE TITLE
Are the unreasonable image  used for training?

### ISSUE THREAD

**Issue by Hwang64** [dvornikita/context_aug#1]
As the fig.7 shows, there are many unreasonable synthesis images, are these images used for training the Faster-RCNN or BlitzNet? Do these images hurt the detection performance?

**Comment by dvornikita** [comment]
We didn't evaluate the contribution of "bad" images into the training process since they are generated on the fly. My intuition is that if the context is wrong, they may hurt the performance to some extent. When the image looks unrealistic, although the context is correct, it helps the final performance, as the results suggest. We augmented for training both Faster-RCNN and BlitzNet. In the letter case, it was found to be more helpful, most likely due to big training batches.

**Comment by Hwang64** [comment]
Thank you for your reply, you say that "We didn't evaluate the contribution of "bad" images into the training process since they are generated on the fly.", does it mean that these "bad" images have been filtered out manually before training the detector and these "bad" image are not use for training detectors?

**Comment by dvornikita** [comment]
Sorry for the ambiguity. What I mean is that we train with all generated images, and since they are generated on-the-fly, we don't know which ones are "good" and which ones are "bad". Hence, we can't separate bad and good ones and measure the impact of either of them to the training. However, as long as the final performance improves, we assume that either we don't have too many bad images, or they don't hurt the training so much.

**Comment by Hwang64** [comment]
ok, thank you for your reply and I am clear now
